title: PieceWeight
description: Smart command-line order calculator for small businesses
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/umairparak/pieceweight
